// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bankoperation.proto

package pl.edu.agh.dsrg.sr.protos;

public final class BankOperationProtos {
  private BankOperationProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BankOperationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .BankOperation.OperationType type = 1;
    boolean hasType();
    pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.OperationType getType();
    
    // required double value = 2;
    boolean hasValue();
    double getValue();
  }
  public static final class BankOperation extends
      com.google.protobuf.GeneratedMessage
      implements BankOperationOrBuilder {
    // Use BankOperation.newBuilder() to construct.
    private BankOperation(Builder builder) {
      super(builder);
    }
    private BankOperation(boolean noInit) {}
    
    private static final BankOperation defaultInstance;
    public static BankOperation getDefaultInstance() {
      return defaultInstance;
    }
    
    public BankOperation getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pl.edu.agh.dsrg.sr.protos.BankOperationProtos.internal_static_BankOperation_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pl.edu.agh.dsrg.sr.protos.BankOperationProtos.internal_static_BankOperation_fieldAccessorTable;
    }
    
    public enum OperationType
        implements com.google.protobuf.ProtocolMessageEnum {
      ADD(0, 0),
      MULTIPLY(1, 1),
      ;
      
      public static final int ADD_VALUE = 0;
      public static final int MULTIPLY_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static OperationType valueOf(int value) {
        switch (value) {
          case 0: return ADD;
          case 1: return MULTIPLY;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<OperationType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<OperationType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OperationType>() {
              public OperationType findValueByNumber(int number) {
                return OperationType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final OperationType[] VALUES = {
        ADD, MULTIPLY, 
      };
      
      public static OperationType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private OperationType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:BankOperation.OperationType)
    }
    
    private int bitField0_;
    // required .BankOperation.OperationType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.OperationType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.OperationType getType() {
      return type_;
    }
    
    // required double value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private double value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getValue() {
      return value_;
    }
    
    private void initFields() {
      type_ = pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.OperationType.ADD;
      value_ = 0D;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, value_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pl.edu.agh.dsrg.sr.protos.BankOperationProtos.internal_static_BankOperation_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pl.edu.agh.dsrg.sr.protos.BankOperationProtos.internal_static_BankOperation_fieldAccessorTable;
      }
      
      // Construct using pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.OperationType.ADD;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.getDescriptor();
      }
      
      public pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation getDefaultInstanceForType() {
        return pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.getDefaultInstance();
      }
      
      public pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation build() {
        pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation buildPartial() {
        pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation result = new pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation) {
          return mergeFrom((pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation other) {
        if (other == pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.OperationType value = pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.OperationType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              value_ = input.readDouble();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .BankOperation.OperationType type = 1;
      private pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.OperationType type_ = pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.OperationType.ADD;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.OperationType getType() {
        return type_;
      }
      public Builder setType(pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.OperationType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.OperationType.ADD;
        onChanged();
        return this;
      }
      
      // required double value = 2;
      private double value_ ;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getValue() {
        return value_;
      }
      public Builder setValue(double value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0D;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:BankOperation)
    }
    
    static {
      defaultInstance = new BankOperation(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:BankOperation)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BankOperation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BankOperation_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023bankoperation.proto\"r\n\rBankOperation\022*" +
      "\n\004type\030\001 \002(\0162\034.BankOperation.OperationTy" +
      "pe\022\r\n\005value\030\002 \002(\001\"&\n\rOperationType\022\007\n\003AD" +
      "D\020\000\022\014\n\010MULTIPLY\020\001B0\n\031pl.edu.agh.dsrg.sr." +
      "protosB\023BankOperationProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BankOperation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BankOperation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BankOperation_descriptor,
              new java.lang.String[] { "Type", "Value", },
              pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.class,
              pl.edu.agh.dsrg.sr.protos.BankOperationProtos.BankOperation.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
